// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAomKbOutOIIZVwoMoUYaQEbKaIx20FM_Y',
    appId: '1:653329787233:web:exampleappid123',
    messagingSenderId: '653329787233',
    projectId: 'fir-ba3eb',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAomKbOutOIIZVwoMoUYaQEbKaIx20FM_Y',
    appId: '1:653329787233:android:e177a3d42531cdf777bd20',
    messagingSenderId: '653329787233',
    projectId: 'fir-ba3eb',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAomKbOutOIIZVwoMoUYaQEbKaIx20FM_Y',
    appId: '1:653329787233:ios:exampleappid123',
    messagingSenderId: '653329787233',
    projectId: 'fir-ba3eb',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAomKbOutOIIZVwoMoUYaQEbKaIx20FM_Y',
    appId: '1:653329787233:ios:exampleappid123',
    messagingSenderId: '653329787233',
    projectId: 'fir-ba3eb',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAomKbOutOIIZVwoMoUYaQEbKaIx20FM_Y',
    appId: '1:653329787233:web:exampleappid123',
    messagingSenderId: '653329787233',
    projectId: 'fir-ba3eb',
  );
}


